name: Run FIT Testing (Internal/Shared)

on:
  workflow_dispatch:
    inputs:
      preset:
        description: FIT preset(s) and/or preset group(s) to generate and execute, comma-separated. (`fit definition list-presets`)
        required: true
        type: string
      collect_extra_diagnostics:
        description: Collect additional diagnostics (includes cbcollect, is slower)
        default: true
        type: boolean
      performer:
        description: Performer image name to use e.g. "java-fit-performer:main".
        required: true
        type: string
      channel:
        description: fit-cli install channel. ("latest" or "ci")
        required: false
        type: string
        default: ci
  workflow_call:
    inputs:
      preset:
        description: FIT preset(s) and/or preset group(s) to generate and execute, comma-separated. (`fit definition list-presets`)
        required: true
        type: string
      collect_extra_diagnostics:
        description: Collect additional diagnostics (includes cbcollect, is slower)
        required: false
        type: boolean
        default: true
      performer:
        description: Performer image name to use e.g. "java-fit-performer:main".
        required: true
        type: string
      channel:
        description: fit-cli install channel. ("latest" or "ci")
        required: false
        type: string
        default: ci

permissions:
  id-token: write   # required for GitHub OIDC

jobs:
  preset-matrix:
    runs-on: ubuntu-latest
    outputs:
      presets: ${{ steps.presets.outputs.presets }}
    steps:
      - name: Preset matrix
        id: presets
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/couchbaselabs/fit-cli/main/install.sh | CHANNEL="${{ inputs.channel }}" bash
          presets=$(fit definition expand-preset-group "$PRESETS" --json)
          echo "presets=$presets" >> "$GITHUB_OUTPUT"
        env:
          PRESETS: ${{ inputs.preset }}

  run-fit:
    needs: preset-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: ${{ fromJson(needs.preset-matrix.outputs.presets) }}
    name: Run FIT (${{ matrix.preset }})
    steps:
      # Assume the AWS role 'fit-cli-role' from account 'cb-sdk' (958525475024), as this has all required AWS permissions.
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::958525475024:role/fit-cli-role
          role-session-name: gha-${{ github.actor }}-${{ github.run_id }}
          audience: sts.amazonaws.com
          retry-max-attempts: 3
          role-duration-seconds: 43200

      - name: Run fit-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/couchbaselabs/fit-cli/main/install.sh | CHANNEL="${{ inputs.channel }}" bash
          args=(preset "${{ matrix.preset }}" --performer "${{ inputs.performer }}")
          if [[ "${{ inputs.collect_extra_diagnostics }}" == "true" ]]; then
            args+=(--cbcollect)
          fi

          fit run "${args[@]}"
