name: Run FIT Testing (Internal/Shared)

on:
  workflow_dispatch:
    inputs:
      preset:
        description: FIT preset type to generate and execute.  (`fit definition list-presets`)
        required: true
        type: string
      collect_extra_diagnostics:
        description: Collect additional diagnostics (includes cbcollect, is slower)
        default: true
        type: boolean
      performer_image_name:
        description: Performer image name to use e.g. "java-fit-performer:main".
        required: true
        type: string
      fit_cli_channel:
        description: fit-cli install channel. ("latest" or "ci")
        required: false
        type: string
        default: ci
  workflow_call:
    inputs:
      preset:
        description: FIT preset type to generate and execute.  (`fit definition list-presets`)
        required: true
        type: string
      collect_extra_diagnostics:
        description: Collect additional diagnostics (includes cbcollect, is slower)
        required: false
        type: boolean
        default: true
      performer_image_name:
        description: Performer image name to use e.g. "java-fit-performer:main".
        required: true
        type: string
      fit_cli_channel:
        description: fit-cli install channel. ("latest" or "ci")
        required: false
        type: string
        default: ci

permissions:
  id-token: write   # required for GitHub OIDC

jobs:
  run-fit:
    runs-on: ubuntu-latest
    steps:
      # Assume the AWS role 'fit-cli-role' from account 'cb-sdk' (958525475024), as this has all required AWS permissions.
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::958525475024:role/fit-cli-role
          role-session-name: gha-${{ github.actor }}-${{ github.run_id }}
          audience: sts.amazonaws.com
          retry-max-attempts: 3
          role-duration-seconds: 43200

      - name: Run fit-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/couchbaselabs/fit-cli/main/install.sh | CHANNEL="${{ inputs.fit_cli_channel }}" bash

          args=(preset "${{ inputs.preset }}" --performer "${{ inputs.performer_image_name }}")
          if [[ "${{ inputs.collect_extra_diagnostics }}" == "true" ]]; then
            args+=(--cbcollect)
          fi

          fit run "${args[@]}"
